on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install dependencies
        run: |
          install.packages(c("remotes","testthat"),dependencies=TRUE)
          remotes::install_github("gtfsway")
        shell: Rscript {0}

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::gtfsway

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("cata_bus_scrape.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add trip_updates.csv
          git add vehicle_updates.csv
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"